pid {{ .DataDir }}/nginx.pid;
daemon off;
worker_processes auto;

error_log syslog:server=unix:/dev/log warn;

events {
    worker_connections 1024;
}

http {
    access_log syslog:server=unix:/dev/log;
    include {{ .AppDir }}/nginx/etc/nginx/mime.types;

    client_body_temp_path {{ .DataDir }}/nginx/client_body_temp;
    proxy_temp_path {{ .DataDir }}/nginx/proxy_temp;
    fastcgi_temp_path {{ .DataDir }}/nginx/fastcgi_temp;
    uwsgi_temp_path {{ .DataDir }}/nginx/uwsgi_temp;
    scgi_temp_path {{ .DataDir }}/nginx/scgi_temp;

    upstream php-handler {
        server unix:{{ .DataDir }}/php-fpm.sock;
    }

    server {
        listen unix:{{ .CommonDir }}/web.socket;
        set_real_ip_from unix:;
        server_name localhost;

        root {{ .AppDir }}/freshrss/p;
        index index.php;

        client_max_body_size 512M;

        include {{ .DataDir }}/config/authelia-location.conf;

        location ~ ^/api/.*\.php(/.*)?$ {
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include {{ .AppDir }}/nginx/etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTPS on;
            fastcgi_param REQUEST_SCHEME https;
            fastcgi_pass php-handler;
            fastcgi_read_timeout 300s;
        }

        location ~ ^.+?\.php(/.*)?$ {
            include {{ .DataDir }}/config/authelia-authrequest.conf;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include {{ .AppDir }}/nginx/etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTPS on;
            fastcgi_param REQUEST_SCHEME https;
            fastcgi_param REMOTE_USER $user;
            fastcgi_pass php-handler;
            fastcgi_read_timeout 300s;
        }

        location / {
            include {{ .DataDir }}/config/authelia-authrequest.conf;
            try_files $uri $uri/ index.php;
        }
    }
}
