[PHP]
engine = On
expose_php = Off
extension_dir = {{ .AppDir }}/php/lib/php/extensions

memory_limit = 256M
max_execution_time = 300
max_input_time = 300
post_max_size = 512M
upload_max_filesize = 512M

date.timezone = UTC
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
log_errors = On

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 60
